application: cooper-redhen
version: 4
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

handlers:
- url: /static
  static_dir: static_files

- url: .*
  script: frontend.py

- url: /upload
  script: uploader.py
  login: admin
  secure: optional
