application: cooper-redhen
version: 2
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

handlers:
- url: /api
  script: frontend.py

- url: /upload
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /docs
  static_dir: docs

- url: /html
  static_dir: html

- url: /(.*)
  static_files: html/\1
  upload: html/index.html
  mime_type: application/xhtml+xml
  
