application: cooper-redhen
version: 1
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

handlers:
- url: /api
  script: frontend.py

- url: /serve
  script: frontend.py

- url: /upload
  script: uploader.py
  login: admin
  secure: optional

- url: /docs
  static_dir: docs

- url: /.*
  static_dir: html/output
