application: cooper-redhen
version: 4
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

handlers:
- url: /html
  static_dir: html

- url: .*
  script: frontend.py

- url: /upload
  script: uploader.py
  login: admin
  secure: optional
