.TH "/home/parent5446/Repositories/cooper-redhen/backend.py" 3 "15 Jul 2010" "Version 0.1" "RedHen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/parent5446/Repositories/cooper-redhen/backend.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSpectrum\fP"
.br
.RI "\fIStore a spectrum and its related data. \fP"
.ti -1c
.RI "class \fBDictProperty\fP"
.br
.RI "\fIStore a dictionary object in the Google Data Store. \fP"
.ti -1c
.RI "class \fBGenericListProperty\fP"
.br
.RI "\fIStore a list object in the Google Data Store. \fP"
.ti -1c
.RI "class \fBMatcher\fP"
.br
.RI "\fIStore data necessary for sorting spectra in a searchable manner. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbackend\fP"
.br
.PP

.RI "\fIProvide functions for identifying a spectrum for an unknown substance using various methods of database searching. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBsearch\fP"
.br
.RI "\fISearch for a spectrum. \fP"
.ti -1c
.RI "def \fBadd\fP"
.br
.RI "\fIAdd a new spectrum to the database. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RedHen from the source code.
