.TH "/home/parent5446/Repositories/cooper-redhen/.ropeproject/config.py" 3 "14 Jul 2010" "Version 0.1" "RedHen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/parent5446/Repositories/cooper-redhen/.ropeproject/config.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBconfig\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBset_prefs\fP"
.br
.ti -1c
.RI "def \fBproject_opened\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RedHen from the source code.
