.TH "config" 3 "14 Jul 2010" "Version 0.1" "RedHen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBset_prefs\fP"
.br
.ti -1c
.RI "def \fBproject_opened\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def config::project_opened ( project)".PP
.nf
This function is called after opening the project.fi
.PP
 
.PP
Definition at line 83 of file config.py.
.SS "def config::set_prefs ( prefs)".PP
.nf
This function is called before opening the project.fi
.PP
 
.PP
Definition at line 4 of file config.py.
.SH "Author"
.PP 
Generated automatically by Doxygen for RedHen from the source code.
