.TH "frontend::MainHandler" 3 "15 Jul 2010" "Version 0.1" "RedHen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frontend::MainHandler \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBget\fP"
.br
.ti -1c
.RI "def \fBpost\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file frontend.py.
.SH "Member Function Documentation"
.PP 
.SS "def get ( self)"
.PP
Definition at line 14 of file frontend.py.
.SS "def post ( self)"
.PP
Definition at line 31 of file frontend.py.

.SH "Author"
.PP 
Generated automatically by Doxygen for RedHen from the source code.
