.TH "redhen::backend" 3 "14 Jul 2010" "Version 0.1" "RedHen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
redhen::backend \- 
.PP
Provide functions for identifying a spectrum for an unknown substance using various methods of database searching.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Provide functions for identifying a spectrum for an unknown substance using various methods of database searching. 

\fBAuthor:\fP
.RS 4
The Cooper Union for the Advancement of the Science and the Arts  http://opensource.org/licenses/lgpl-3.0.html GNU Lesser General Public License v3.0  Copyright (c) 2010, Cooper Union (Some Right Reserved) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for RedHen from the source code.
