.TH "redhen" 3 "14 Jul 2010" "Version 0.1" "RedHen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
redhen \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbackend\fP"
.br
.PP

.RI "\fIProvide functions for identifying a spectrum for an unknown substance using various methods of database searching. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RedHen from the source code.
