.TH "uploader::JDXFile" 3 "14 Jul 2010" "Version 0.1" "RedHen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uploader::JDXFile \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "tuple \fBfileName\fP = db.BlobProperty()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file uploader.py.
.SH "Member Data Documentation"
.PP 
.SS "tuple \fBfileName\fP = db.BlobProperty()\fC [static]\fP"
.PP
Definition at line 10 of file uploader.py.

.SH "Author"
.PP 
Generated automatically by Doxygen for RedHen from the source code.
